# Generated by Django 2.2.5 on 2019-10-17 11:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeid', models.CharField(max_length=20)),
                ('bikelocation', models.CharField(max_length=20)),
                ('statement', models.BooleanField(default=False)),
                ('bikeprice', models.FloatField()),
                ('isused', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bike',
                'ordering': ['id'],
            },
            managers=[
                ('bikeObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('userpassword', models.CharField(max_length=20)),
                ('telephone', models.IntegerField()),
                ('userlocation', models.CharField(max_length=20, null=True)),
                ('balance', models.FloatField(null=True)),
                ('renttime', models.DateTimeField(null=True)),
                ('returntime', models.DateTimeField(null=True)),
                ('authority', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'costumer',
                'ordering': ['id'],
            },
            managers=[
                ('costumerObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manid', models.CharField(max_length=20)),
                ('manname', models.CharField(max_length=20)),
                ('manpassword', models.CharField(max_length=20)),
                ('authority', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'manager',
                'ordering': ['id'],
            },
            managers=[
                ('manageObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opid', models.CharField(max_length=20)),
                ('opname', models.CharField(max_length=20)),
                ('oppassword', models.CharField(max_length=20)),
                ('authority', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'operator',
                'ordering': ['id'],
            },
            managers=[
                ('operatorObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
